CREATE TABLE IF NOT EXISTS "best_cart"
(
    id      bigint generated by default as identity,
    changed timestamp,
    created timestamp,
    status  varchar(255),
    user_id bigint,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS "best_cart_product_items"
(
    "cart_entity_id"   bigint not null,
    "product_items_id" bigint not null,
    primary key ("cart_entity_id", "product_items_id")
);

CREATE TABLE IF NOT EXISTS "best_order"
(
    id       bigint generated by default as identity,
    cart_id  bigint,
    changed  timestamp,
    created  timestamp,
    discount decimal(19, 2),
    price    decimal(19, 2),
    status   varchar(255),
    total    decimal(19, 2),
    user_id  bigint,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS "best_product"
(
    id          bigint generated by default as identity,
    changed     timestamp,
    created     timestamp,
    description varchar(255),
    name        varchar(255),
    price       decimal(19, 2),
    status      varchar(255),
    type        varchar(255),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS "best_property_item"
(
    id         bigint generated by default as identity,
    price      decimal(19, 2),
    product_id bigint,
    quantity   integer,
    total      decimal(19, 2),
    product_type
               varchar(255),
    cart_id    bigint,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS "best_users"
(
    id          bigint generated by default as identity,
    authorities varchar(255),
    changed     timestamp,
    created     timestamp,
    email       varchar(254),
    family      varchar(50),
    name        varchar(50),
    status      varchar(255),
    username    varchar(50) not null,
    primary key (id)
);